import { type ReactNode } from 'react';
import { type Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <div className='container m-2 mx-auto px-2'>{children}</div>
      </body>
    </html>
  );
}
