import { type ReactNode } from 'react';
import { type Metadata } from 'next';
import Link from 'next/link';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='min-h-screen w-full'>
        <div className='container mx-auto flex h-screen w-full flex-col px-2'>
          <header className='mb-14 mt-2 flex'>
            <Link className='-rotate-6 text-4xl text-poimandres-yellow' href='/'>
              Snippets!
            </Link>
            <Link className='bg-poimandres-lightgreen' href='/snippets/new'>
              New
            </Link>
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
